### PR TITLE
Update .gitignore file

### PR DESCRIPTION
**Pull request by singhaditya28**
Updated for better security and stability

### CODE REVIEW

**Comment by zeroxoneb** [comment]
Many of the files listed here don't exist in this repo, nor likely would exist in this repo.  I see your comments on another FB repo: https://github.com/facebookincubator/ptr/pull/95 

I'll be honest, I don't see what benefit this adds.  The current `.gitignore` properly ignores all the transient build artifacts that shouldn't be committed.

**Comment by singhaditya28** [comment]
If you have read the comment you would understand that there are many os specific files present which are never present on the repo but created on user's device. Thus, please accept my PR

**Comment by zeroxoneb** [comment]
> many os specific files present which are never present on the repo but created on user's device

I don't understand what you are referring too here.   If you can provide explicit examples of this happening in this repo, I'd be happy to reconsider, but as of now, we don't need this. Thanks.

**Comment by singhaditya28** [comment]
When I tested out this and many other projects like this one, I have encountered each of the file listed in the file. So, please merge this.  I am updating as many files I can and they are accepting it too as they understood this is important. So, please! 👍 😃

**Pull request closed without merging**
